# Generated by Django 5.2 on 2025-04-17 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('berberApp', '0003_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='barber',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
