# Generated by Django 5.2 on 2025-04-17 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('berberApp', '0006_unavailableslot'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='unavailableslot',
            unique_together={('barber', 'date')},
        ),
        migrations.RemoveField(
            model_name='unavailableslot',
            name='time',
        ),
    ]
