# Generated by Django 5.2 on 2025-04-30 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('berberApp', '0007_alter_unavailableslot_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
    ]
